"""initiation

Revision ID: 240530a9ed30
Revises: 0f761fe7f075
Create Date: 2025-03-23 01:50:04.134312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240530a9ed30'
down_revision = '0f761fe7f075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=64), nullable=False),
    sa.Column('user_lname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_fname'),
    sa.UniqueConstraint('user_lname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
